### PR TITLE
V2 attempt two

### PR DESCRIPTION
**Pull request by drewjbartlett**
@mgred I don't want to scare you off with this but I finally went ahead and rewrote rapid to be _almost_ what I wanted it to be. Everything is extracted into short and concise methods. _Almost_ everything is under test. But I ran my tests continually while I refactored to ensure the current implementation did not break. I used `// @ts-check` on these files to get them prepped for typescript. 

I am nearly finished getting this to a good place and then if you're not scared away we can work together to add in TS while keeping the files `.js` if possible. I need to rewrite the debugger and some more tests and then we will be golden to get v2 out the door! If you still want to help, while you implement TS into this, I can update the documentation :D.

Let me know your thoughts! I also don't expect that you have to give this PR a thorough review since I have all my tests passing and made a butt ton of changes.

### Version 2 Checklist

 - [ ] Add TypeScript Support while maintaining `.js` files
 - [ ] Properly declare and import type definitions #41 
-  [x] Fix all tests #46 
 - [x] `api` renamed to `http`
 - [x] swap `qs` for `qs-stringify` since we only use that method https://www.npmjs.com/package/qs-stringify
- [x] Allow for other promise-based http services to be used in place of axios with injection
- [x] Fix nasty inheritance chain
- [ ] Extract debugger to allow easier testing
- [ ] Extract custom routes into package
- [ ] Rewrite version 2 docs to reflect updates
- [ ] Rewrite version 2 docs in nuxt (and maybe markdown)
- [ ] Rewrite v1 tests and add more test coverage
- [ ] Rewrite Auth to be a mixin
- [ ] Fix polluted params issue when where params send twice
- [ ] Add build tool to minify or gzip files on dist
- [ ] Remove `prepublish` hook and replace with: Use `prepare` for build steps and `prepublishOnly` for upload-only.
- [ ] Add plugin system to allow syntax like `rapid.use(customRouter)`

### CODE REVIEW

**Comment by mgred** [comment]
@drewjbartlett Wow that's massive work, I will review and merge asap. I will also update with `master`, since the branch seems to be a bit behind.

**Comment by mgred** [comment]
@drewjbartlett Alright this thing is merged. :boom:
> If you still want to help, while you implement TS into this, I can update the documentation

Sure, that sounds good. Let's do it!!

I would like to define more detailed tasks and put them into issues to have a better overview.

**Comment by drewjbartlett** [comment]
@mgred I wasn't quite ready to make a merge which was totally my bad for specifying :D. I can revert

**Comment by mgred** [comment]
@drewjbartlett, easy let me know

**Pull request merged**
