### PR TITLE
add .editorconfig and edit .gitignore

### PR DESCRIPTION
**Pull request by yihou**
add .editorconfig to make sure the coding style is consistent throughout.
update .gitignore to avoid commit IDE config files

### CODE REVIEW

**Comment by drewjbartlett** [comment]
@yihou thanks for this! Could you write a description of what this is doing so I can know what to look for? Also - did you get the latest changes from this branch that was made last week?

**Comment by mgred** [comment]
@yihou I beg your pardon for my later review, i did not notice this was still pending. I just submitted.

**Comment by yihou** [comment]
@drewjbartlett My bad, just removed the prefix paths

**Comment by yihou** [comment]
@mgred no worries, I got busy the these few weeks too, btw, I did change it to `@babel/preset-env`

**Comment by mgred** [comment]
@yihou I just noticed that there are still some `js` files in your branch.

* `src/core/core.js`
* `test/interceptors.test.js`

It's important to note that the `v2-refactor` branch misses the 'Interceptor feature' which will most likely change, since the new version will work with adaptors to allow `axios` to be replaced by another http client. So I think we don't need this feature anyways. This would also apply to the changes in `default.ts`.
Also, the feature itself has a lack not to support error interceptors as explained by @M3psipax above. So I guess we will rework this so we can use the proposed workaround.

Sorry, I saw this way too late.

**Comment by drewjbartlett** [comment]
@yihou @mgred have been on a trip but will look at this asap. Thanks a TON!

**Comment by yihou** [comment]
@mgred sorry, just saw your message, might not know what to do with the `core.js` and `test/interceptors.test.js` yet.

**Comment by mgred** [comment]
@yihou I think you can just delete them.

**Comment by drewjbartlett** [comment]
@mgred @yihou thanks for the hard work on this. I have been buried with work but I am excited to hop back on this with you guys! 

To the point of the interceptors. I may be worthwhile to write a new feature that still gives some support for this. I'm not sure what that looks like but I do know it was a largely requested feature

**Comment by drewjbartlett** [comment]
@yihou you are the man! Thanks for this work. Sorry it took me so long. v2 is gonna be amazing!

**Pull request merged**
